# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Federico @ Makers'
tagline:          '- a timeline of me learning coding.'
description:      blog
url:              http://federicomaffei.github.io

author:
  name:           Federico Maffei
  url:            http://federicomaffei.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
