# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            federico @ makers
tagline:          a timeline of me learning coding
url:              http://federicomaffei.github.io
paginate:         5
baseurl:	      /
author:
  name:           Federico Maffei
  url:            https://twitter.com/foltoc
  email:          federico.maffei@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
