# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            fedtechrants ->
tagline:          another beginner's blog on programming computers.
url:              http://federicomaffei.github.io
paginate:         5
baseurl:	      /
author:
  name:           Federico Maffei
  url:            https://github.com/federicomaffei
  email:          federico.maffei@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
