# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        date

# Setup
title:            federico @ makers
tagline:          a timeline of me learning coding
url:              http://federicomaffei.github.io
shorturl:         federicomaffei.github.io

author:
  name:           Federico Maffei
  url:            https://twitter.com/foltoc
  email:          federico.maffei@gmail.com

paginate:         5

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
